# For key-to-key remapping
modmap:
  - name: main remaps
    remap:
     rightalt: rightctrl
     rightctrl: rightalt
     CapsLock:
       held: leftctrl
       alone: esc
       alone_timeout_millis: 150
# For key seq mappings
#keymap:
